create database priyank3 ;
use priyank3;
use priyank;
show tables;
select * from deposit;
select count(AMOUNT) FROM deposit;
select count(AMOUNT) FROM deposit WHERE BNAME =' KAROLBAGH';
SELECT BNAME , max(AMOUNT) FROM deposit group by BNAME;
select * from customers;
select count(CNAME) FROM customers;
select count(CITY) FROM customers;
use priyank2;
create table SUPPLIER AS SELECT * FROM employee;
select * from SUPPLIER;
SELECT * FROM employee;
create TABLE SUP1 AS select emp_no , emp_name from employee;
select * from SUP1;
create table SUP2 AS SELECT * FROM employee where 1=2;
select * from SUP2;
insert into SUP2 SELECT * FROM employee where emp_name like '_n___';
delete from SUP1;
delete FROM SUP2 where emp_no = 103;
alter table SUP2 rename to SUP3;
DROP TABLE SUP1;
UPDATE employee set dept_no = 10 where emp_name like '_m%';
update eployee set emp_name='Jhon' where emp_no = 103;